# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  # measure against bitrot
  # also rotates docker images monthly, by pushing new docker images
  # the rotation will happen by renovate
  # rotate the images at the end of the 3th quarter of the month, 
  # to avoid duplicate rotations at the beginning/middle of the month, 
  # as the source docker images are also mostly rotated once a month
  schedule:
    - cron: "0 0 21 * *"

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

concurrency:
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  changes:
    name: "ðŸ” Detect Changes"
    runs-on: ubuntu-slim
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
      docker: ${{ steps.filter.outputs.docker }}
      workflows: ${{ steps.filter.outputs.lint }}
    steps:
      - name: ðŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ðŸ” Check for changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            docker:
              - '.github/docker/**'
            workflows:
              - '.github/workflows/*.yml'

      - name: Output branch name
        id: branch
        run: |
          echo "branch=${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT

  label-pr:
    if: github.event_name == 'pull_request'
    name: "ðŸ·ï¸ PR"
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config file
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-slim
    steps:
      - uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af # v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  typos:
    uses: ./.github/workflows/typos-reusable.yml

  docker:
    name: "ðŸ³"
    needs: changes
    if: needs.changes.outputs.docker == 'true'
    permissions:
      contents: read
      packages: write # Needed to push to GHCR
    uses: ./.github/workflows/docker-reusable.yml
    with:
      branch: ${{ needs.changes.outputs.branch }}

  all-required-green: # This job does nothing and is only used for the branch protection
    name: CI Status
    runs-on: ubuntu-latest
    needs:
      - label-pr
      - docker
      - typos
    if: always()
    steps:
      - name: Check whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@2765efec08f0fd63e83ad900f5fd75646be69ff6
        with:
          allowed-skips: >-
            label-pr,
            docker
          jobs: ${{ toJSON(needs) }}
