name: Reusable clang-format check workflow

on:
  workflow_call:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/actions-github-clang-format:v1@sha256:5cb39907471ee7126e1f9addeb02762b1c58b52c9d6756d31c1e7f8c3a8a08b1 # v1
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ğŸ“ Check clang-format
        shell: bash
        run: |
          find . -regex '.*\.\(cpp\|hpp\)' -exec clang-format --dry-run --Werror {} +
