name: Reusable clang-format check workflow

on:
  workflow_call:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/actions-github-clang-format:v1@sha256:99a7d75dd5d2d39224f51477d896654032869af8d7f7aee887376d26c124c560 # v1
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ğŸ“ Check clang-format
        shell: bash
        run: |
          find . -regex '.*\.\(cpp\|hpp\)' -exec clang-format --dry-run --Werror {} +
