# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Coverity Scan Reusable"
on:
  workflow_call:
    secrets:
      COVERITY_EMAIL:
        required: true
      COVERITY_TOKEN:
        required: true
    inputs:
      extra-deps:
        required: false
        type: string
        default: ""

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - name: üîÑ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: üõ†Ô∏è Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq -y \
            build-essential \
            cmake \
            curl \
            ninja-build \
            ${{ inputs.extra-deps }}

      - name: ‚öôÔ∏è Configure using CMake and Ninja
        run: cmake -S . -B build -G Ninja

      - name: ‚ö°Scan with Coverity
        uses: vapier/coverity-scan-action@2068473c7bdf8c2fb984a6a40ae76ee7facd7a85 # v1.8.0
        with:
          email: ${{ secrets.COVERITY_EMAIL }}
          token: ${{ secrets.COVERITY_TOKEN }}
          command: ninja
          working-directory: "${{ github.workspace }}/build"

      - name: üì§ Upload analysis tarball
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ github.event.repository.name }}_coverity_scan_upload_${{ github.sha }}
          path: build/cov-int.tgz
          if-no-files-found: error
