name: Reusable gersemi cmake format workflow

on:
  workflow_call:

jobs:
  gersemi-cmake-check:
    name: ğŸ“ CMake
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/actions-github-gersemi:v1@sha256:d2996437cb3ab02f092df96548c681357f8383edeff592c7af5349e8980a8dff
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ğŸ“ Check cmake format
        run: gersemi --check --diff .
