name: Reusable gersemi cmake format workflow

on:
  workflow_call:

jobs:
  gersemi-cmake-check:
    name: ğŸ“ CMake
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/actions-github-gersemi:v1@sha256:f82c7860694527684bfa164a90c8c14626693cbd05b6e67702e1fa5b576e5a12
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ğŸ“ Check cmake format
        run: gersemi --check --diff .
