name: Reusable gersemi cmake format workflow

on:
  workflow_call:

jobs:
  gersemi-cmake-check:
    name: ğŸ“ CMake
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/actions-github-gersemi:v1@sha256:2bcd643138c4dcaa99bca4ed6b0aa179d74af0b8d972267d918eb2685bc2abb4
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ğŸ“ Check cmake format
        run: gersemi --check --diff .
