name: Reusable gersemi cmake format workflow

on:
  workflow_call:

jobs:
  gersemi-cmake-check:
    name: ğŸ“ CMake
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/actions-github-gersemi:v1@sha256:308fa4a6894a3e0b22903d48c1ef65e68964882c88e07ddb585574b16dac5fe8
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ğŸ“ Check cmake format
        run: gersemi --check --diff .
