name: Reusable gersemi cmake format workflow

on:
  workflow_call:

jobs:
  cmake-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/actions-github-gersemi:v1@sha256:1e12250a2b23897bbac434dfc3556a7bde3afa2b7235420278dcac65d125157d
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: ğŸ“ Check cmake format
        run: gersemi --check --diff .
