name: Reusable gersemi cmake format workflow

on:
  workflow_call:

jobs:
  gersemi-cmake-check:
    name: ğŸ“ CMake
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/actions-github-gersemi:v1@sha256:8b66bd52c9540b99aa5f82f498845e2a4360611e23596f902356d6a0b9088a18
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ğŸ“ Check cmake format
        run: gersemi --check --diff .
