name: Reusable gersemi cmake format workflow

on:
  workflow_call:

jobs:
  gersemi-cmake-check:
    name: ğŸ“ CMake
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/actions-github-gersemi:v1@sha256:02b8ec7af1353917705974ddec5b2d36b9741e87bd4ce4d04e72f6b058faebcc
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ğŸ“ Check cmake format
        run: gersemi --check --diff .
