name: Reusable gersemi cmake format workflow

on:
  workflow_call:

jobs:
  cmake-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hrzlgnm/actions-github-gersemi:v1@sha256:2539da6bbd1f2b372b5a084afc1b95510d119d7d8f5c04e4a106e94291f5c334
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: ğŸ“ Check cmake format
        run: gersemi --check --diff .
