# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Reusable ci typos workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  typos:
    name: ğŸ“
    runs-on: ubuntu-slim
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ğŸ“ Check spelling using typos-action
        uses: crate-ci/typos@bb4666ad77b539a6b4ce4eda7ebb6de553704021 # v1.42.0
