# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Reusable ci typos workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  typos:
    name: ğŸ“
    runs-on: ubuntu-slim
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ğŸ“ Check spelling using typos-action
        uses: crate-ci/typos@78bc6fb2c0d734235d57a2d6b9de923cc325ebdd # v1.43.4
